name: gnn
channels:
  - conda-forge
  - defaults
dependencies:
  - configargparse=1.5.3
  - fenics=2019.1.0
  - fenics-dijitso=2019.1.0
  - fenics-dolfin=2019.1.0
  - fenics-ffc=2019.1.0
  - fenics-fiat=2019.1.0
  - fenics-libdolfin=2019.1.0
  - fenics-ufl=2019.1.0
  - hdf5=1.10.6
  - ipykernel=6.4.1
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jupyter=1.0.0
  - jupyter_client=7.0.6
  - jupyter_console=6.4.0
  - jupyter_core=4.9.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - matplotlib=3.5.0
  - matplotlib-base=3.5.0
  - matplotlib-inline=0.1.2
  - notebook=6.0.3
  - numpy=1.21.4
  - pillow=8.4.0
  - pip=21.3.1
  - pkg-config=0.29.2
  - pkgconfig=1.5.5
  - pybind11=2.8.1
  - pybind11-global=2.8.1
  - pyparsing=3.0.4
  - python=3.7.12
  - scipy=1.7.3
  - tqdm=4.62.3
  - yaml=0.2.5
  - pip:
    - cmocean==2.0
    - configparser==5.2.0
    - dolfin-adjoint==2019.1.0
    - h5py==3.6.0
    - imageio==2.13.3
    - pandas==1.3.4
    - partd==1.2.0
    - pathtools==0.1.2
    - promise==2.3
    - protobuf==3.19.1
    - psutil==5.8.0
    - pyyaml==6.0
    - scikit-image==0.19.0
    - scikit-learn==1.0.1
    - subprocess32==3.5.4
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - toolz==0.11.2
    - torchmeta==1.8.0
    - wandb==0.12.7
    - setuptools==59.5.0
