# Table 1
#CEM by GNS(1-step) n_composed=1,2,3,4 meas 24,34,44,54 steps (tmuxid =ID1,2,...)
python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_autoregress" --method_type "GNS_autoregress" --GNS_output_size 2 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_autoregress.pt" --dataset 'nbody-2' --design_method "CEM" --is_batch_for_GNS True --val_batch_size 500 --max_design_steps 1000 --coef 10 --gamma 2 --coef_max_noise 0 --coef_grad 1e-3 --n_composed 1 --N 1000 --Ne 100 --is_batch_for_GNS True --gpuid 1
python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_autoregress" --method_type "GNS_autoregress" --GNS_output_size 2 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_autoregress.pt" --dataset 'nbody-2' --design_method "CEM" --is_batch_for_GNS True --val_batch_size 500 --max_design_steps 1000 --coef 10 --gamma 2 --coef_max_noise 0 --coef_grad 1e-3 --n_composed 2 --N 1000 --Ne 100 --is_batch_for_GNS True --gpuid 1
python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_autoregress" --method_type "GNS_autoregress" --GNS_output_size 2 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_autoregress.pt" --dataset 'nbody-2' --design_method "CEM" --is_batch_for_GNS True --val_batch_size 500 --max_design_steps 1000 --coef 10 --gamma 2 --coef_max_noise 0 --coef_grad 1e-3 --n_composed 3 --N 1000 --Ne 100 --is_batch_for_GNS True --gpuid 1
python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_autoregress" --method_type "GNS_autoregress" --GNS_output_size 2 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_autoregress.pt" --dataset 'nbody-2' --design_method "CEM" --is_batch_for_GNS True --val_batch_size 500 --max_design_steps 1000 --coef 10 --gamma 2 --coef_max_noise 0 --coef_grad 1e-3 --n_composed 4 --N 1000 --Ne 100 --is_batch_for_GNS True --gpuid 2

#CEM by GNS n_composed=1,2,3,4 meas 24,34,44,54 steps (tmuxid =ID5,6,...)
python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_direct" --method_type "GNS_direct" --GNS_output_size 46 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_direct.pt" --design_method "CEM"  --is_batch_for_GNS True --val_batch_size 500 --max_design_steps 1000 --coef 10 --gamma 2 --coef_max_noise 0 --coef_grad 1e-3 --n_composed 1 --N 1000 --Ne 100  --gpuid 2
python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_direct" --method_type "GNS_direct" --GNS_output_size 46 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_direct.pt" --design_method "CEM"  --is_batch_for_GNS True --val_batch_size 500 --max_design_steps 1000 --coef 10 --gamma 2 --coef_max_noise 0 --coef_grad 1e-3 --n_composed 2 --N 1000 --Ne 100  --gpuid 2
python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_direct" --method_type "GNS_direct" --GNS_output_size 46 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_direct.pt" --design_method "CEM"  --is_batch_for_GNS True --val_batch_size 500 --max_design_steps 1000 --coef 10 --gamma 2 --coef_max_noise 0 --coef_grad 1e-3 --n_composed 3 --N 1000 --Ne 100  --gpuid 2
python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_direct" --method_type "GNS_direct" --GNS_output_size 46 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_direct.pt" --design_method "CEM"  --is_batch_for_GNS True --val_batch_size 500 --max_design_steps 1000 --coef 10 --gamma 2 --coef_max_noise 0 --coef_grad 1e-3 --n_composed 4 --N 1000 --Ne 100  --gpuid 2

#CEM by Unet(1-step) n_composed=1,2,3,4 meas 24,34,44,54 steps (tmuxid =ID7,8,...)
python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_Unet_single" --method_type "Unet_single_step" --checkpoint_path "/zhangtao/cindm/checkpoint_path/Unet_cond-1_rollout-1_bodies-2.pt" --design_method "CEM" --max_design_steps 1000 --coef 1 --gamma 2 --coef_max_noise 0 --val_batch_size 500 --n_composed 1 --N 1000 --Ne 100 --gpuid 2
python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_Unet_single" --method_type "Unet_single_step" --checkpoint_path "/zhangtao/cindm/checkpoint_path/Unet_cond-1_rollout-1_bodies-2.pt" --design_method "CEM" --max_design_steps 1000 --coef 1 --gamma 2 --coef_max_noise 0 --val_batch_size 500 --n_composed 2 --N 1000 --Ne 100 --gpuid 2
python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_Unet_single" --method_type "Unet_single_step" --checkpoint_path "/zhangtao/cindm/checkpoint_path/Unet_cond-1_rollout-1_bodies-2.pt" --design_method "CEM" --max_design_steps 1000 --coef 1 --gamma 2 --coef_max_noise 0 --val_batch_size 500 --n_composed 3 --N 1000 --Ne 100 --gpuid 2
python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_Unet_single" --method_type "Unet_single_step" --checkpoint_path "/zhangtao/cindm/checkpoint_path/Unet_cond-1_rollout-1_bodies-2.pt" --design_method "CEM" --max_design_steps 1000 --coef 1 --gamma 2 --coef_max_noise 0 --val_batch_size 500 --n_composed 4 --N 1000 --Ne 100 --gpuid 2

#CEM by Unet n_composed=1,2,3,4 meas 24,34,44,54 steps (#############################)
python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_Unet" --method_type "Unet" --checkpoint_path "/zhangtao/cindm/checkpoint_path/Unet_cond-1_rollout-23_bodies-2.pt" --design_method "CEM" --max_design_steps 1000 --coef 1 --gamma 2 --coef_max_noise 0 --val_batch_size 500 --n_composed 1 --N 1000 --Ne 100 --gpuid 2
python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_Unet" --method_type "Unet" --checkpoint_path "/zhangtao/cindm/checkpoint_path/Unet_cond-1_rollout-23_bodies-2.pt" --design_method "CEM" --max_design_steps 1000 --coef 1 --gamma 2 --coef_max_noise 0 --val_batch_size 500 --n_composed 2 --N 1000 --Ne 100 --gpuid 2
python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_Unet" --method_type "Unet" --checkpoint_path "/zhangtao/cindm/checkpoint_path/Unet_cond-1_rollout-23_bodies-2.pt" --design_method "CEM" --max_design_steps 1000 --coef 1 --gamma 2 --coef_max_noise 0 --val_batch_size 500 --n_composed 3 --N 1000 --Ne 100 --gpuid 2
python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_Unet" --method_type "Unet" --checkpoint_path "/zhangtao/cindm/checkpoint_path/Unet_cond-1_rollout-23_bodies-2.pt" --design_method "CEM" --max_design_steps 1000 --coef 1 --gamma 2 --coef_max_noise 0 --val_batch_size 500 --n_composed 4 --N 1000 --Ne 100 --gpuid 2



#Backprop by GNS(1-step) n_composed=1,2,3,4 meas 24,34,44,54 steps (tmuxid =ID11,12,...)
python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_autoregress" --method_type "GNS_autoregress" --GNS_output_size 2 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_autoregress.pt" --design_method "backprop" --val_batch_size 500 --max_design_steps 1000 --coef 10 --gamma 2 --coef_max_noise 0 --coef_grad 1e-3 --n_composed 1 --gpuid 5
python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_autoregress" --method_type "GNS_autoregress" --GNS_output_size 2 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_autoregress.pt" --design_method "backprop" --val_batch_size 500 --max_design_steps 1000 --coef 10 --gamma 2 --coef_max_noise 0 --coef_grad 1e-3 --n_composed 2 --gpuid 2
python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_autoregress" --method_type "GNS_autoregress" --GNS_output_size 2 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_autoregress.pt" --design_method "backprop" --val_batch_size 500 --max_design_steps 1000 --coef 10 --gamma 2 --coef_max_noise 0 --coef_grad 1e-3 --n_composed 3 --gpuid 2
python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_autoregress" --method_type "GNS_autoregress" --GNS_output_size 2 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_autoregress.pt" --design_method "backprop" --val_batch_size 500 --max_design_steps 1000 --coef 10 --gamma 2 --coef_max_noise 0 --coef_grad 1e-3 --n_composed 4 --gpuid 2

#Backprop by GNS n_composed=1,2,3,4 meas 24,34,44,54 steps (tmuxid =ID13,14,...)
python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_direct" --method_type "GNS_direct" --GNS_output_size 46 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_direct.pt" --design_method "backprop" --val_batch_size 500 --max_design_steps 1000 --coef 10 --gamma 2 --coef_max_noise 0 --coef_grad 1e-3 --n_composed 1 --gpuid 2
python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_direct" --method_type "GNS_direct" --GNS_output_size 46 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_direct.pt" --design_method "backprop" --val_batch_size 500 --max_design_steps 1000 --coef 10 --gamma 2 --coef_max_noise 0 --coef_grad 1e-3 --n_composed 2 --gpuid 2
python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_direct" --method_type "GNS_direct" --GNS_output_size 46 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_direct.pt" --design_method "backprop" --val_batch_size 500 --max_design_steps 1000 --coef 10 --gamma 2 --coef_max_noise 0 --coef_grad 1e-3 --n_composed 3 --gpuid 2
python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_direct" --method_type "GNS_direct" --GNS_output_size 46 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_direct.pt" --design_method "backprop" --val_batch_size 500 --max_design_steps 1000 --coef 10 --gamma 2 --coef_max_noise 0 --coef_grad 1e-3 --n_composed 4 --gpuid 2

#Backprop by Unet(1-step) n_composed=1,2,3,4 meas 24,34,44,54 steps (tmuxid =ID15,16,...)
python inference/inverse_design_1d_baseline.py --date_time "2023-02-04_1d_baseline_Unet_single" --method_type "Unet_single_step" --checkpoint_path "/zhangtao/cindm/checkpoint_path/Unet_cond-1_rollout-1_bodies-2.pt" --design_method "backprop" --max_design_steps 1000 --coef 1 --gamma 2 --coef_max_noise 0 --val_batch_size 500 --n_composed 1 --gpuid 2
python inference/inverse_design_1d_baseline.py --date_time "2023-02-04_1d_baseline_Unet_single" --method_type "Unet_single_step" --checkpoint_path "/zhangtao/cindm/checkpoint_path/Unet_cond-1_rollout-1_bodies-2.pt" --design_method "backprop" --max_design_steps 1000 --coef 1 --gamma 2 --coef_max_noise 0 --val_batch_size 500 --n_composed 2 --gpuid 2
python inference/inverse_design_1d_baseline.py --date_time "2023-02-04_1d_baseline_Unet_single" --method_type "Unet_single_step" --checkpoint_path "/zhangtao/cindm/checkpoint_path/Unet_cond-1_rollout-1_bodies-2.pt" --design_method "backprop" --max_design_steps 1000 --coef 1 --gamma 2 --coef_max_noise 0 --val_batch_size 500 --n_composed 3 --gpuid 2
python inference/inverse_design_1d_baseline.py --date_time "2023-02-04_1d_baseline_Unet_single" --method_type "Unet_single_step" --checkpoint_path "/zhangtao/cindm/checkpoint_path/Unet_cond-1_rollout-1_bodies-2.pt" --design_method "backprop" --max_design_steps 1000 --coef 1 --gamma 2 --coef_max_noise 0 --val_batch_size 500 --n_composed 4 --gpuid 2

#Backprop by Unet n_composed=1,2,3,4 meas 24,34,44,54 steps (tmuxid =ID17,18,...)
python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_Unet" --method_type "Unet" --checkpoint_path "/zhangtao/cindm/checkpoint_path/Unet_cond-1_rollout-23_bodies-2.pt" --design_method "backprop"  --max_design_steps 1000 --coef 1 --gamma 2 --coef_max_noise 0  --coef_grad 1.0 --val_batch_size 500 --n_composed 1 --gpuid 2
python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_Unet" --method_type "Unet" --checkpoint_path "/zhangtao/cindm/checkpoint_path/Unet_cond-1_rollout-23_bodies-2.pt" --design_method "backprop"  --max_design_steps 1000 --coef 1 --gamma 2 --coef_max_noise 0  --coef_grad 1.0 --val_batch_size 500 --n_composed 1 --gpuid 2
python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_Unet" --method_type "Unet" --checkpoint_path "/zhangtao/cindm/checkpoint_path/Unet_cond-1_rollout-23_bodies-2.pt" --design_method "backprop"  --max_design_steps 1000 --coef 1 --gamma 2 --coef_max_noise 0  --coef_grad 1.0 --val_batch_size 500 --n_composed 1 --gpuid 2
python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_Unet" --method_type "Unet" --checkpoint_path "/zhangtao/cindm/checkpoint_path/Unet_cond-1_rollout-23_bodies-2.pt" --design_method "backprop"  --max_design_steps 1000 --coef 1 --gamma 2 --coef_max_noise 0  --coef_grad 1.0 --val_batch_size 500 --n_composed 1 --gpuid 2

#Table 2
#CEM by GNS(1-step)
# python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_autoregress_bodies-4"  --dataset "nbody-4" --method_type "GNS_autoregress" --GNS_output_size 2 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_autoregress.pt" --design_method "CEM" --val_batch_size 500 --max_design_steps 1000 --coef 10 --gamma 2 --coef_max_noise 0 --coef_grad 1e-4 --n_composed 1 --N 1000 --Ne 100 --is_batch_for_GNS True --gpuid 2
# python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_autoregress_bodies-4"  --dataset "nbody-4" --method_type "GNS_autoregress" --GNS_output_size 2 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_autoregress.pt" --design_method "CEM" --val_batch_size 500 --max_design_steps 1000 --coef 10 --gamma 2 --coef_max_noise 0 --coef_grad 1e-4 --n_composed 3 --N 1000 --Ne 100 --is_batch_for_GNS True --gpuid 2
# python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_autoregress_bodies-4"  --dataset "nbody-8" --method_type "GNS_autoregress" --GNS_output_size 2 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_autoregress.pt" --design_method "CEM" --val_batch_size 500 --max_design_steps 1000 --coef 10 --gamma 2 --coef_max_noise 0 --coef_grad 1e-4 --n_composed 1 --N 1000 --Ne 100 --is_batch_for_GNS True --gpuid 2
# python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_autoregress_bodies-4"  --dataset "nbody-8" --method_type "GNS_autoregress" --GNS_output_size 2 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_autoregress.pt" --design_method "CEM" --val_batch_size 500 --max_design_steps 1000 --coef 10 --gamma 2 --coef_max_noise 0 --coef_grad 1e-4 --n_composed 3 --N 1000 --Ne 100 --is_batch_for_GNS True --gpuid 2

#CEM by GNS
# python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_direct_bodies-4"  --dataset "nbody-4" --method_type "GNS_direct" --GNS_output_size 46 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_direct.pt" --design_method "CEM" --val_batch_size 500 --max_design_steps 1000 --coef 1 --gamma 2 --coef_max_noise 0 --coef_grad 2e-5 --n_composed 1 --N 1000 --Ne 100 --is_batch_for_GNS True --gpuid 2
# python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_direct_bodies-4"  --dataset "nbody-4" --method_type "GNS_direct" --GNS_output_size 46 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_direct.pt" --design_method "CEM" --val_batch_size 500 --max_design_steps 1000 --coef 1 --gamma 2 --coef_max_noise 0 --coef_grad 2e-5 --n_composed 3 --N 1000 --Ne 100 --is_batch_for_GNS True --gpuid 2
# python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_direct_bodies-4"  --dataset "nbody-8" --method_type "GNS_direct" --GNS_output_size 46 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_direct.pt" --design_method "CEM" --val_batch_size 500 --max_design_steps 1000 --coef 1 --gamma 2 --coef_max_noise 0 --coef_grad 2e-5 --n_composed 1 --N 1000 --Ne 100 --is_batch_for_GNS True --gpuid 2
# python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_direct_bodies-4"  --dataset "nbody-8" --method_type "GNS_direct" --GNS_output_size 46 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_direct.pt" --design_method "CEM" --val_batch_size 500 --max_design_steps 1000 --coef 1 --gamma 2 --coef_max_noise 0 --coef_grad 2e-5 --n_composed 3 --N 1000 --Ne 100 --is_batch_for_GNS True --gpuid 2


#Backprop by GNS(1-step)
# python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_autoregress_bodies-4"  --dataset "nbody-4" --method_type "GNS_autoregress" --GNS_output_size 2 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_autoregress.pt" --design_method "backprop" --val_batch_size 500 --max_design_steps 1000 --coef 10 --gamma 2 --coef_max_noise 0 --coef_grad 1e-4 --n_composed 1 --gpuid 2
# python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_autoregress_bodies-4"  --dataset "nbody-4" --method_type "GNS_autoregress" --GNS_output_size 2 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_autoregress.pt" --design_method "backprop" --val_batch_size 500 --max_design_steps 1000 --coef 10 --gamma 2 --coef_max_noise 0 --coef_grad 1e-4 --n_composed 3 --gpuid 2
# python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_autoregress_bodies-4"  --dataset "nbody-8" --method_type "GNS_autoregress" --GNS_output_size 2 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_autoregress.pt" --design_method "backprop" --val_batch_size 500 --max_design_steps 1000 --coef 10 --gamma 2 --coef_max_noise 0 --coef_grad 1e-4 --n_composed 1 --gpuid 2
# python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_autoregress_bodies-4"  --dataset "nbody-8" --method_type "GNS_autoregress" --GNS_output_size 2 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_autoregress.pt" --design_method "backprop" --val_batch_size 500 --max_design_steps 1000 --coef 10 --gamma 2 --coef_max_noise 0 --coef_grad 1e-4 --n_composed 3 --gpuid 2

#Backprop by GNS
# python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_direct_bodies-4"  --dataset "nbody-4" --method_type "GNS_direct" --GNS_output_size 46 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_direct.pt" --design_method "backprop" --val_batch_size 500 --max_design_steps 1000 --coef 1 --gamma 2 --coef_max_noise 0 --coef_grad 2e-5 --n_composed 1 --gpuid 2
# python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_direct_bodies-4"  --dataset "nbody-4" --method_type "GNS_direct" --GNS_output_size 46 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_direct.pt" --design_method "backprop" --val_batch_size 500 --max_design_steps 1000 --coef 1 --gamma 2 --coef_max_noise 0 --coef_grad 2e-5 --n_composed 3 --gpuid 2
# python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_direct_bodies-4"  --dataset "nbody-8" --method_type "GNS_direct" --GNS_output_size 46 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_direct.pt" --design_method "backprop" --val_batch_size 500 --max_design_steps 1000 --coef 1 --gamma 2 --coef_max_noise 0 --coef_grad 2e-5 --n_composed 1 --gpuid 2
# python inference/inverse_design_1d_baseline.py --date_time "2024-02-04_1d_baseline_GNS_direct_bodies-4"  --dataset "nbody-8" --method_type "GNS_direct" --GNS_output_size 46 --checkpoint_path "/zhangtao/cindm/checkpoint_path/GNS_cond-1_rollout-23_bodies-2_direct.pt" --design_method "backprop" --val_batch_size 500 --max_design_steps 1000 --coef 1 --gamma 2 --coef_max_noise 0 --coef_grad 2e-5 --n_composed 3 --gpuid 2