DATASET_ABS: 'nbody_gns_dataset'
TRAIN_DIR: 'Nbody/train'
VAL_DIR: 'Nbody/valid'
ROLLOUT_STEPS: 240
N_HIS: 4
PRED_STEPS: 1
MAX_VAL: 30
KINEMATIC_PARTICLE_ID: 1
NUM_PARTICLE_TYPES: 1
SOLVER:
  BASE_LR: 1.0e-4
  MIN_LR: 1.0e-6
  WEIGHT_DECAY: 0.0
  MAX_ITERS: 5e6
  WARMUP_ITERS: 0
  VAL_INTERVAL: 25000
  BATCH_SIZE: 1
  LR_DECAY_INTERVAL: 5e6
NET:
  PARTICLE_EMB_SIZE: 16
  MAX_EDGE_PER_PARTICLE: 6
  SELF_EDGE: True
  NODE_FEAT_DIM_IN: 30
  EDGE_FEAT_DIM_IN: 3
  GNN_LAYER: 5
  HIDDEN_SIZE: 128
  OUT_SIZE: 2
  NOISE: 0.00000067
  RADIUS: 0.015